name: Token Check Test

on:
  workflow_dispatch:
    inputs:
      release_token:
        description: 'Your release token'
        required: true

jobs:
  token-check:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          printf "The secret was $release_token\n"
          printf "The provided token was ${{ inputs.release_token }}\n"
          echo "Success!"
        if: "${{ github.event.inputs.release_token }} == ${{ env.release_token }}"
        env:
          release_token: "wowsosecret"

  regular-release:
    needs: token-check
    runs-on: ubuntu-latest
    steps:
      - name: Build if token check succeeded
        run: |
          echo All Good!
